### PR TITLE
DeepSpeed to DeepSpeed converter for changing tp/pp

### PR DESCRIPTION
**Pull request by tjruwase**
Addressing #23 
@stas00, FYI

### CODE REVIEW

**Comment by stas00** [comment]
@tjruwase, it appears that EAI have also been doing work in that direction, albeit in one direction only: many to 1, but it appears not to work exactly from a quick read of the issue.

https://github.com/EleutherAI/gpt-neox/pull/466

So perhaps some collaboration can be had if they have already solved some of the problems you have encountered and vice versa.

**Comment by tjruwase** [comment]
@stas00, can you confirm that it is okay to close this because of https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/238

**Comment by stas00** [comment]
yes, it'd be easier to test directly in the BigScience fork and then backport to the MSFT fork. So it's definitely ok to close this one.

**Comment by stas00** [comment]
this PR has moved to https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/239

**Pull request closed without merging**
