### PR TITLE
support llama pretraining

### PR DESCRIPTION
**Pull request by LydiaXiaohongLi**
Support for llama pretraining with pipeline parallel and tensor parallel. Llama model implementation following huggingface, https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py

### CODE REVIEW

**Comment by LydiaXiaohongLi** [comment]
@microsoft-github-policy-service agree [company="Ahrefs"]

**Comment by LydiaXiaohongLi** [comment]
@microsoft-github-policy-service agree company="Ahrefs"

**Comment by leiwen83** [comment]
Hi,

I don't see any example goes with this llama pretain, like https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples/pretrain_gpt3_175B.sh

Does it mean that simply "python pretrain_llama.py" would function well?

**Comment by zhongwenjie01** [comment]
Could you give an example how to train llama?

**Comment by conglongli** [comment]
Thank you @LydiaXiaohongLi for your PR. This is Conglong Li from DeepSpeed team and I will help to test and review your PR. As mentioned by other users above, in order to actually test the training we would need your help to provide a training script (something like this https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples/MoE/ds_pretrain_gpt_1.3B_dense.sh) and a deepspeed config (something like this https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples/MoE/ds_config_gpt_TEMPLATE.json). If we can get a script and config that you tested work on your side, we will then be able to try to reproduce the training on our side to verify. Thank you. Looking forward to your reply.

**Comment by 2018211801** [comment]
upup~

**Comment by LydiaXiaohongLi** [comment]
Hi, @conglongli, 
I have created the llama pretraining script at examples/pretrain_llama_distributed.sh (the ds config is included in the script too).
I have revised my code to avoid a seperate llama modeling (following huggingface's style), but instead make it configurable for the existing gpt style models to support the various model features of llama, including rotary embedding, rms laynorm, and others. 
I have tested a few scenarios myself, such as deepspeed pp+tp; deepspeed zeros; and many others on llama model setup and gpt2 model setup. 
Thanks in advance for your effort for reviewing the PR.

**Comment by suc16** [comment]
@LydiaXiaohongLi 大佬看下megatron/model/__init__.py
`from .llama_model import LlamaModel, LlamaModelPipe`
似乎应该删掉

**Comment by fssqawj** [comment]
Great job! Is there any way to **continue pre-training** a llama model based on this?

**Comment by LydiaXiaohongLi** [comment]
@fssqawj 
I would think so, if you specify properly the --load parameter in the training script, to point to the pretrained llama checkpoint, the existing megatron-deepspeed framework should be able to handle that, see: https://github.com/microsoft/Megatron-DeepSpeed/blob/7491937ef43f96d167a7e0b91c1e3be8d5397d17/megatron/training.py#L543

**Comment by LydiaXiaohongLi** [comment]
@suc16 , 谢谢指出 是需要取掉。

**Comment by conglongli** [comment]
@LydiaXiaohongLi Hi sorry about my recent silence, I actually was working on syncing this repo with Megatron-LM, which is just finished. During this sync we actually replaced the main branch by renaming branches, which is why this PR now points to main_before_rebase branch. Could you take a look at the new main branch, modify your integration as needed (for example in the sync we had merged Megatron's rotary_pos_embedding.py), and create a new PR to point to the new main branch? Thank you so much and sorry about the inconvenience.

**Comment by FelliYang** [comment]
> @fssqawj I would think so, if you specify properly the --load parameter in the training script, to point to the pretrained llama checkpoint, the existing megatron-deepspeed framework should be able to handle that, see:
> 
> https://github.com/microsoft/Megatron-DeepSpeed/blob/7491937ef43f96d167a7e0b91c1e3be8d5397d17/megatron/training.py#L543

感谢大佬！目前开源社区里能获取到的llama权重格式分别是原生的pytorch格式和huggingface转换后的格式，请问这两种格式的模型想要在megatron-deepspeed里面加载并使用你的代码预训练，需要先转换成megatron的格式吗？

**Comment by Sirius222** [comment]
Hi, how to evaluate the model performance under this framework？

**Comment by zdaiot** [comment]
@LydiaXiaohongLi Hello, how is the bookcorpus_train_1m_text_sentence dataset converted?
In addition, how to convert the weight?
Thanks a lot

**Pull request closed without merging**
