### PR TITLE
Fixed incorrect argument supplied to deepspeed init

### PR DESCRIPTION
**Pull request by SulRash**
Following up on the GitHub issue I posted:

https://github.com/microsoft/Megatron-DeepSpeed/issues/244

I wrote in my fix.

### CODE REVIEW

**Comment by samadejacobs** [comment]
@SulRash, many thanks for your PR. As rightly noted, this is a backward compatibility issue. A more generalized (backward compatible) fix would look something like this:
```
if hasattr(mpu, 'get_sequence_parallel_group'):
     dpg = mpu.get_sequence_parallel_group()
elif hasattr(mpu, 'get_data_parallel_group'):
     dpg = mpu.get_data_parallel_group()
else:
     dpg = None
with deepspeed.zero.Init(data_parallel_group=dpg, …….)
```

**Review by samadejacobs — CHANGES_REQUESTED** [review]
@SulRash, many thanks for your PR. As rightly noted, this is a backward compatibility issue. A more generalized (backward compatible) fix would look something like this:
```
if hasattr(mpu, 'get_sequence_parallel_group'):
     dpg = mpu.get_sequence_parallel_group()
elif hasattr(mpu, 'get_data_parallel_group'):
     dpg = mpu.get_data_parallel_group()
else:
     dpg = None
with deepspeed.zero.Init(data_parallel_group=dpg, …….)

**Comment by SulRash** [comment]
@samadejacobs thanks for the suggestion, that is much cleaner. I added the changes requested.

**Review by samadejacobs — APPROVED** [review]
Thank you for your contributions.

**Pull request merged**
