### PR TITLE
Loading attention directly on device

### PR DESCRIPTION
**Pull request by jomayeri**
Create attention mask directly on the GPU.

### CODE REVIEW

**Comment by jomayeri** [comment]
@samadejacobs and @tohtana When @tjruwase and I were debugging the issue of performance degradation running Megatron on H100 we narrowed it down loading the attention mask directly on the device. We noticed this was a change made for the long sequence length commit and wanted to start a discussion on the reason for the change. Thanks.

**Comment by minjiaz** [comment]
Hi @jomayeri ,

The attention map offloading is created for support training with massive sequence lengths. In the long sequence training scenario, it is only called once during the initialization because the mask does not change. But during inference, it can get repeatedly called for each generation as new masks need to be created, so the overhead is high. I feel a fix could be to make this conditional, e.g., do attention mask generation only when sequence parallelism is enabled and perhaps only when the sequence length exceeds a given threshold (e.g., 64k). @chengming-zhang, can you take at this issue?

**Comment by zhangsmallshark** [comment]
Hi @jomayeri  when sequence length is short. It will not cause any problems. But when sequence length is long, it will cause out of memory errors.  I will enable offload only when the sequence length exceeds a given threshold. I will fix it.

**Comment by zhangsmallshark** [comment]
Hi @jomayeri, your change has already disabled attention map offload. I can use your change to test on H100. I will create new PR to improve performance.

**Comment by jomayeri** [comment]
Thanks @zhangsmallshark, I'll close this PR then.

**Comment by tjruwase** [comment]
> Hi @jomayeri when sequence length is short. It will not cause any problems. But when sequence length is long, it will cause out of memory errors. I will enable offload only when the sequence length exceeds a given threshold. I will fix it.

@zhangsmallshark, @minjiaz, @tohtana, here is my two cents. I think it would be better to control offloading with a command line option such as `--offload-attention-map`.  This would allow users to more conveniently study the memory/performance tradeoffs regardless of the sequence length and HBM size. I feel picking a sequence length threshold is tricky because of the rapid changes in model and hardware capabilities.

**Comment by zhangsmallshark** [comment]
@tjruwase thanks. I agree with your idea.

**Comment by minjiaz** [comment]
Hi @tjruwase, that was a great idea.

**Pull request closed without merging**
