### PR TITLE
fix checkpointing forward bug

### PR DESCRIPTION
**Pull request by HandH1998**
We (@sleepcoo) found a bug in [https://github.com/microsoft/Megatron-DeepSpeed/blob/41116e063ed09417e36e185ba92b7ae817f0f4df/megatron/model/transformer.py#L1704](url). 
image
When we enabled checkpointing activations (`--recompute-granularity full --recompute-method uniform`), the model failed to forward.  We located the bug in `_checkpointed_forward` function. `x_` is a tuple, which contains a hidden_state and a loss, but only the hidden_state should be sent to `layer`. 
To fix the bug, we used the `custom` function in [https://github.com/microsoft/Megatron-DeepSpeed/blob/41116e063ed09417e36e185ba92b7ae817f0f4df/megatron/model/transformer.py#L1673](url) and corrected the subsequent code accordingly.

### CODE REVIEW

**Comment by conglongli** [comment]
@HandH1998 As explained in https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/README.md, we didn't expect DeepSpeed to automatically work with Megatron's new checkpointing mechanism. I can review this PR and accept it after testing (might need some time), but before that it'd be great if you could help to check whether this example with old checkpointing mechanism (https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/ds_pretrain_gpt_125M.sh) still works after applying your changes.

**Comment by sleepcoo** [comment]
> @HandH1998 As explained in https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/README.md#notestodos, we didn't expect DeepSpeed to work with Megatron's new checkpointing mechanism. I can review this PR and accept it after testing (might need some time), but before that it'd be great if you could help to check whether this example with old checkpointing mechanism (https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/ds_pretrain_gpt_125M.sh) still works after applying your changes.

Hello @conglongli , do you have any plans to develop a bpipe line recently? We are happy to assist if needed.

**Comment by HandH1998** [comment]
> > > @HandH1998 As explained in https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/README.md#notestodos, we didn't expect DeepSpeed to work with Megatron's new checkpointing mechanism. I can review this PR and accept it after testing (might need some time), but before that it'd be great if you could help to check whether this example with old checkpointing mechanism (https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/ds_pretrain_gpt_125M.sh) still works after applying your changes.
> > 
> > 
> > Hello @conglongli , do you have any plans to develop a bpipe line recently? We are happy to assist if needed.
> 
> I honestly don't know what you mean about "bpipe line". For any ask of adding separate features, please open a separate issue to request that.
> 
> On the other hand, @HandH1998 @sleepcoo shall we first focus on this PR? I'm still waiting for your answer to my question: Whether your PR will affect the old checkpointing mechanism? Did you test our example script (https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/ds_pretrain_gpt_125M.sh) after your changes.

I tested this, it can still work. In fact, we only changed the code of megatron's activation recomputing, and it will not affect the old checkpointing mechanism.

**Comment by conglongli** [comment]
> I tested this, it can still work. In fact, we only changed the code of megatron's activation recomputing, and it will not affect the old checkpointing mechanism.

@HandH1998 Thanks for confirming! In this case, could you actually commit a modified version of https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/ds_pretrain_gpt_125M.sh as an example of how to use the new checkpointing mechanism enabled by this PR? I would like to compare them, and if the new one is better, I think it make sense to modify our documentation/scripts to use the new mechanism enabled by your PR :) Thank you!

**Comment by HandH1998** [comment]
> > I tested this, it can still work. In fact, we only changed the code of megatron's activation recomputing, and it will not affect the old checkpointing mechanism.
> 
> @HandH1998 Thanks for confirming! In this case, could you actually commit a modified version of https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/ds_pretrain_gpt_125M.sh as an example of how to use the new checkpointing mechanism enabled by this PR? I would like to compare them, and if the new one is better, I think it make sense to modify our documentation/scripts to use the new mechanism enabled by your PR :) Thank you!

Actually, it is not a new checkpointing mechanism in our PR. We only fixed a bug when using megatron activation checkpointing, i.e., `--recompute-granularity full --recompute-method uniform`. I added a new script to test this in `examples_deepspeed/rebase/new_ds_pretrain_gpt_125M.sh`. Hope you guys could check it.

**Review by conglongli — APPROVED** [review]

**Comment by conglongli** [comment]
@HandH1998 @sleepcoo After testing your PR on my side, I had approved and merged it. When comparing the two checkpointing mechanisms, I found that their performance are rather similar, but still it's good for users to have another option. I added one line at the end of https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/README.md to document your contribution, and I also slightly modified your script to change it to 1.3B training in order to have a more reasonable performance comparison. Thanks again for your contribution.

On the other hand, for the "bpipe line" you mentioned, we welcome 3P users' new feature contribution as long as you could first open an issue as a proposal of this feature and explain its benefits. Detailed guideline is at https://github.com/microsoft/DeepSpeed/blob/master/CONTRIBUTING.md#new-feature-contribution-guidelines (it's in the DeepSpeed repo but it also applies to our other repos). Thank you.

**Comment by HandH1998** [comment]
> @HandH1998 @sleepcoo After testing your PR on my side, I had approved and merged it. When comparing the two checkpointing mechanisms, I found that their performance are rather similar, but still it's good for users to have another option. I added one line at the end of https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/README.md to document your contribution, and I also slightly modified your script to change it to 1.3B training in order to have a more reasonable performance comparison. Thanks again for your contribution.
> 
> On the other hand, for the "bpipe line" you mentioned, we welcome 3P users' new feature contribution as long as you could first open an issue as a proposal of this feature and explain its benefits. Detailed guideline is at https://github.com/microsoft/DeepSpeed/blob/master/CONTRIBUTING.md#new-feature-contribution-guidelines (it's in the DeepSpeed repo but it also applies to our other repos). Thank you.

I think you should remove `--deepspeed `option (304 line in `examples_deepspeed/rebase/ds_pretrain_gpt_1.3B_megatron_checkpointing`) to use megatron checkpointing. Please check it to ensure that you make a appropriate comparison. Thank you.

**Comment by conglongli** [comment]
> > @HandH1998 @sleepcoo After testing your PR on my side, I had approved and merged it. When comparing the two checkpointing mechanisms, I found that their performance are rather similar, but still it's good for users to have another option. I added one line at the end of https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/README.md to document your contribution, and I also slightly modified your script to change it to 1.3B training in order to have a more reasonable performance comparison. Thanks again for your contribution.
> > On the other hand, for the "bpipe line" you mentioned, we welcome 3P users' new feature contribution as long as you could first open an issue as a proposal of this feature and explain its benefits. Detailed guideline is at https://github.com/microsoft/DeepSpeed/blob/master/CONTRIBUTING.md#new-feature-contribution-guidelines (it's in the DeepSpeed repo but it also applies to our other repos). Thank you.
> 
> I think you should remove `--deepspeed `option (304 line in `examples_deepspeed/rebase/ds_pretrain_gpt_1.3B_megatron_checkpointing`) to use megatron checkpointing. Please check it to ensure that you make a appropriate comparison. Thank you.

@HandH1998 First of all, I was strictly following the script you originally provided, where you did include `--deepspeed ` option (https://github.com/microsoft/Megatron-DeepSpeed/pull/225/commits/5a7df9695b05ef43832122f5070fc9613bd4c552).

After reading the code changes again, I see what you mean: the Megatron-LM's activation checkpointing mechanism that this PR fixed is still not compatible with DeepSpeed. I had merged a new PR https://github.com/microsoft/Megatron-DeepSpeed/pull/235 where I fixed the scripts to make a fair comparison, and the conclusion is that we would still recommend users to use the older checkpointing both due to the similar performance, and (more importantly) because the new mechanism is not compatible with DeepSpeed.

**Pull request merged**
