### PR TITLE
fixing legacy mpu usages

### PR DESCRIPTION
**Pull request by clumsy**
`mpu` seem to have been replaces by `parallel_state` and `tensor_parallel`.

With these changes I'm able to run BERT model with the following additional tweak (not included in this PR).

In `megatron/model/transformer.py`:
```
# assert self.activation_func == F.gelu
```

### CODE REVIEW

**Comment by clumsy** [comment]
For your consideration, @conglongli.

**Comment by clumsy** [comment]
Funny, the reason the assertion is failing is because DeepSpeed's FLOPS profiler using bogus activation function: [here](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/profiling/flops_profiler/profiler.py#L809)

The state of `self.activation_func` at the time of failure:
```
<function wrapFunc.<locals>.newFunc at 0x7fc8f25cf670>
```

I'll address this separately.

**Review by conglongli — APPROVED** [review]
LGTM, although mpu is actually still applicable as an alias https://github.com/microsoft/Megatron-DeepSpeed/blob/9e72d571f49296d7002889cc19692d97a5b0f92e/megatron/core/__init__.py#L7

**Comment by conglongli** [comment]
Yeah I agree, better to use parallel_state from now on (esp for new code)

**Pull request merged**
