### PR TITLE
Rebase Megatron-LM

### PR DESCRIPTION
**Pull request by zhangsmallshark**

### CODE REVIEW

**Comment by zhangsmallshark** [comment]
@microsoft-github-policy-service agree

**Comment by conglongli** [comment]
Note to anyone with question: this is an effort by DeepSpeed team and our intern @zhangsmallshark to rebase Megatron-DeepSpeed. This is just the initial step, and there are still a lot of todos including conflict resolution and actual training tests. So it's not recommended to try the above branches right now. Due to the complexity, we will first do this rebase in a separate "rebase" branch, and will later merge into main branch after more tests and user feedback.

**Comment by conglongli** [comment]
Closing this PR as we decided to sync with Megatron-LM in a different way.

**Comment by clumsy** [comment]
> Closing this PR as we decided to sync with Megatron-LM in a different way.

Could you please elaborate which way it's going to be and when to expect it?

I'm interested in contributing if the help is needed.

**Comment by conglongli** [comment]
@clumsy This PR was a more ad-hoc merge by our intern. We decided to switch back to the recommended way (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork, basically git merge Megatron-LM). The initial merge is actually finished in https://github.com/microsoft/Megatron-DeepSpeed/tree/rebase, but we are still working on debugging, testing and final refactor, but it should be finished soon hopefully next week. We will then merge it to main branch (with a backup branch of current main), and then you are more than welcomed to try it and contribute by bug report/fixes :)

**Comment by clumsy** [comment]
Sounds great, @conglongli! Meanwhile I'll give the branch a try.

**Comment by conglongli** [comment]
> Sounds great, @conglongli! Meanwhile I'll give the branch a try.

@clumsy Sure, but please be aware that the current branch still has bugs here and there.

**Comment by fortanyo** [comment]
@conglongli Any update to the rebasing?

**Pull request closed without merging**
